### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by alloc33** [ggandor/leap-spooky.nvim#17]
Installed (lunarvim, lazy.nvim):

```lua
		{
			"ggandor/leap-spooky.nvim",
			config = function()
				require("leap-spooky").setup()
			end,
		},
```

bindings like `yirw` don't work it quits operator pending mode on `r`. What am I doing wrong? (leap is already installed and I'm using it constantly)

**Comment by ggandor** [comment]
What does `:omap irw` show?

**Comment by alloc33** [comment]
> What does `:omap irw` show?

<img width="649" alt="image" src="https://github.com/ggandor/leap-spooky.nvim/assets/45129790/f39a36d8-1cc5-4e25-b6cb-6f14581ee301">

**Comment by ggandor** [comment]
I have no idea then. Maybe try to install it without lazy.nvim. (Simply clone the repo to somewhere, `vim.opt.runtimepath:append('<path-to-repo-folder>')`, then call `setup`.)

**Comment by ggandor** [comment]
Wait a minute, isn't yours the same problem as #15, #16 (timeoutlen)?

**Comment by alloc33** [comment]
> Wait a minute, isn't yours the same problem as #15, #16 (timeoutlen)?

yeah, its it... bye bye which-key )
