### ISSUE TITLE
Integration with mini.ai

### ISSUE THREAD

**Issue by Sleepful** [ggandor/leap-spooky.nvim#18]
Would be super duper awesome.
I mean, this plugin is already super duper awesome.
So I guess integrating it with the text objects form mini.ai would be superdupersuper awesome.

I have no idea what it takes but here are the mini.ai docs https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-ai.txt

**Comment by Sleepful** [comment]
I guess this is similar to https://github.com/ggandor/leap-spooky.nvim/issues/1 and also the last "planned feature" bullet point in README.

**Comment by ggandor** [comment]
Yep, we have thought about that: #11, #12.
