### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Sleepful** [ggandor/leap-spooky.nvim#19]
It stopped working for me idk why

if I do `:omap irw` I see it does not find spooky:
```
o  i             <Lua 731: ~/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1120>
                 Inside textobject
Press ENTER or type command to continue
```

**Comment by Sleepful** [comment]
going back to `b9dcc30866e6b916b2d8f3e2f3d6a2c207fffd73` seems to fix the issue:

`:omap irw`

```
o  irw         * <Lua 586: ~/.local/share/nvim/lazy/leap-spooky.nvim/lua/leap-spooky.lua:128>

```

**Comment by ggandor** [comment]
I messed up with https://github.com/ggandor/leap-spooky.nvim/commit/73c8fe21776275b54e875a89aae240d60b8b6af1 (that made `riw` etc. the default), but the very last commit should fix that.

**Comment by Sleepful** [comment]
Thanks @ggandor !
