### ISSUE TITLE
Launch remote yanking from a different keybinding

### ISSUE THREAD

**Issue by agenbite** [ggandor/leap-spooky.nvim#25]
Hi, I'm loving this plugin! I'm mostly a newbie in nvim and I was wondering how can I launch the remote operations with a different key than 's'. My usecase is that I use nvim as a pager inside other app and "s" is already bound. A :leap-remote-yank command that I could bind to, e.g. C-s, would solve my issue. Is that even possible?

**Comment by ggandor** [comment]
Hi! I don't understand, you trigger remote yanking with `y` (spooky just defines text objects - `:help text-objects`). E.g. to yank a remote inner word (`iw`), via targeting an `ab` pair in it, you type: `yirwab` (= `y` [operator] + `irw` [special text object defined by spooky] + `ab` [the actual leaping motion to mark the reference point]).

**Comment by agenbite** [comment]
Hi, thanks for your reply and sorry for the vagueness in my question. I'm using things like the `yirwab` and it's great. What I was wondering is if there is a way to launch leap-spooky in directly from the ex-line. 

The usecase is that I'm using vim as a pager inside my mail client. Then, while I'm reading a message, I'd like to `yarw` (copy a remote word or line), but `r` is bound to replying the email, so I can't do it. It'd be great to be able to call the remote selection part of leap-spooky as an independent command.

**Comment by agenbite** [comment]
I just discovered a way to enable a passthrough mode in my mail client which allows me to do everything I want in the pager. Closing this now, thank you so much!
