### ISSUE TITLE
Custom text objects overwrite the default ones

### ISSUE THREAD

**Issue by auron95** [ggandor/leap-spooky.nvim#26]
Hello, thank you for this awesome plugin!
I wanted to point out a bug for the custom text objects feature: adding custom text objects will overwrite the default ones. This is apparently because `vim.tbl_extend` on line 73 does not concatenate arrays, but merges tables, so adding n custom text objects replaces the first n default text objects.

**Comment by ggandor** [comment]
Wow, no one has reported this for two months. Thanks!
