### ISSUE TITLE
Error on load of plugin

### ISSUE THREAD

**Issue by PetitBandit** [ggandor/leap-spooky.nvim#3]
![CleanShot 2022-11-04 at 16 42 20@2x](https://user-images.githubusercontent.com/32488040/200017309-3fcf2001-35ef-4ec0-b5a6-96f21f5891cd.png)

Hello, first off, i love this plugin,
I do have this error on launch of neovim, can somebody help with this please ? 
Thanks in advance

**Comment by ggandor** [comment]
Update setup: https://github.com/ggandor/leap-spooky.nvim#setup.

**Comment by PetitBandit** [comment]
Thanks !
