### ISSUE TITLE
Doc bug: README.md does not clarify what difference between `r` and `m` is

### ISSUE THREAD

**Issue by elmarsto** [ggandor/leap-spooky.nvim#8]
What's remote? What's magnetic? When to use one or the other? Why these terms?

**Comment by raine** [comment]
The examples in the README are nice, but would really appreciate a full list of possible affixes and with the letters expanded with their meaning.

**Comment by kisuryoza** [comment]
Remote allows you manipulation with objects without touching cursor, while magnetic puts your cursor to where manipulation happened.

**Comment by zhengpd** [comment]
Agree the doc doesn't say much about the letters meaning. README mentions `drr[leap]` to delete line. Anyone knows  what each `r` means here? I guess one of them is 'remote'.

**Comment by ggandor** [comment]
> Anyone knows what each r means here? I guess one of them is 'remote'.

It doesn't "mean" anything, but meant to resemble native Vim operators, where you duplicate the given letter for the linewise version (eg. `dd` or `yy`). (Not terribly logical though, since, after all, Spooky creates text objects, not operators.)

**Comment by ggandor** [comment]
(Hopefully) resolved by 3e94046.
